services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=gb_laravel
      - DB_USERNAME=jane
      - DB_PASSWORD=12345
    entrypoint: ["sh", "/docker-entrypoint.sh"]

  db:
    image: mysql:8.0.32
    container_name: laravel-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gb_laravel
      MYSQL_USER: jane
      MYSQL_PASSWORD: 12345
      TZ: UTC
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s
    cap_add:
      - SYS_NICE

  nginx:
    image: nginx:latest
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - app

  npm:
    image: node:18-alpine
    container_name: vite
    working_dir: /var/www/html
    ports:
      - "5173:5173"
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    depends_on:
      - app
    command: >
      sh -c "npm install && npm run build"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
